---
# Install this role
- name: Converge
  hosts: all

  pre_tasks:

    - name: Workaround to get host IP inside docker
      shell: hostname -I | cut -d' ' -f1
      register: hostname_ip
      check_mode: false
      changed_when: false
      tags:
        # Ignore [306] Shells that use pipes should set the pipefail option
        - skip_ansible_lint

  roles:

    - role: ome.docker

    - role: ansible-role-minio-s3-gateway
      minio_s3_gateway_remote_endpoint: "http://{{ hostname_ip.stdout }}:12345"
      minio_s3_gateway_access_key: remote-access
      minio_s3_gateway_secret_key: remote-secret

  tasks:

    - name: remote s3 server
      become: true
      docker_container:
        image: "{{ minio_s3_gateway_minio_image }}"
        command: server /data
        name: minio-s3-gateway-remote
        env:
          MINIO_ACCESS_KEY: remote-access
          MINIO_SECRET_KEY: remote-secret
        ports:
          - "12345:9000"
        volumes:
          - /data/minio:/data
